# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Work Secure Academy
tagline:          'IT Training'
description:      'Training for IT and CyberSecurity Professionals'
url:              https://worksecure.online
baseurl:          /

author:
  name:           'Work Secure Academy'
  url:            https://linkedin.com/company/work-secure-academy

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
