# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Work Secure Academy
tagline:          'Training for IT Pros
description:      'On-demand and In-person training for IT Pros'
url:              http://worksecure.online
baseurl:          /

author:
  name:           'Work Secure Academy'
  url:            https://linkedin.com/company/worksecureacademy

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Work-Secure-Academy/
